name: "oml_reranking_dataset"
args:
#  dataset_root: /path/to/dataset/   # use your dataset root here
  dataframe_name: df.csv
#  embeddings_cache_dir: ${args.dataset_root} # CACHE EMBEDDINGS PRODUCED BY BASELINE FEATURE EXTRACTOR
  cache_size: 0
  batch_size_inference: 128
  num_workers: 2
  precision: 16
  accelerator: cpu

  feature_extractor:
    name: vit
    args:
      normalise_features: True
      use_multi_scale: False
      weights: null # or /path/to/extractor.ckpt  # <---- specify path to baseline feature extractor
      arch: vits16

  transforms_extraction:
    name: norm_resize_hypvit_torch
    args:
      im_size: 224
      crop_size: 224

  transforms_train:
    name: augs_hypvit_torch
    args:
      im_size: 224
