name: extractor_with_mlp
args:
  mlp_features: [384]
  weights: vits16_224_mlp_384_inshop
  extractor:
    name: vit
    args:
      normalise_features: False
      use_multi_scale: False
      weights: vits16_dino
      arch: vits16
