name: extractor_with_mlp
args:
  mlp_features: [384]
  weights: null
  extractor:
    name: vit
    args:
      normalise_features: False
      use_multi_scale: False
      weights: null
      arch: vits16
