postfix: classification

seed: 42
precision: 32
gpus:
  - 1

dataframe_name: df.csv
dataset_root: /nydl/data/DeepFashion_InShop/
logs_root: /nydl/logs/DeepFashion_InShop/
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

im_size_train: 256
im_size_val: 224
im_pad_ratio_train: 0.0
im_pad_ratio_val: 0.0
num_workers: 20
cache_size: 100000

sampler: null

bs_val: 512
bs_train: 128
max_epochs: 10000
valid_period: 1

metric_args:
  cmc_top_k: [1]
  map_top_k: [5]

augs: broadface

emb_size: 128

model:
  name: resnet_broadface
  args:
    embedding_size: ${emb_size}


criterion:
  name: arcface
  args:
    in_features: ${emb_size}
    out_features: 3985
    scale_factor: 64.0
    margin: 0.50

optimizer:
  name: adam
  args:
    lr: 1e-4
    weight_decay: 1e-5

scheduling:
  scheduler_interval: epoch
  scheduler_frequency: 1
  scheduler:
     name: multi_step
     args:
       gamma: 0.2
       milestones:
         - 40
         - 60
         - 80


# To use neptune you should also specify NEPTUNE_API_TOKEN in
# .env file or via `export NEPTUNE_API_TOKEN=...`
neptune_project: NEWYORKER/similarity-api


hydra_dir: ${logs_root}/${logs_folder}/

tags:
  - ${postfix}
  - deepfashion

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
    - file://../../configs
