postfix: ""

seed: 42
precision: 32
accelerator: cpu
devices: 1

dataset_root: /Users/alex/Library/Caches/oml/mock_dataset
logs_root: /Users/alex/Downloads/
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

num_workers: 0
max_epochs: 1000
valid_period: 1000
bs_val: 256

top_n: 5

freeze_n_epochs: 0

extractor:
  name: vit
  args:
    normalise_features: True
    use_multi_scale: False
    weights: vits16_sop
    arch: vits16

optimizer:
  name: adam
  args:
    lr: 1e-3

scheduling: null

sampler:
  name: category_balance
  args:
    n_labels: 4
    n_instances: 3
    n_categories: 1
    resample_labels: True
    weight_categories: True

#transforms_train:
#  name: augs_hypvit_torch
#  args:
#    im_size: 224
#    min_scale: 0.8

transforms_train:
  name: norm_resize_hypvit_torch
  args:
    im_size: 32
    crop_size: 32

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 32
    crop_size: 32

transforms_extraction:
  name: norm_resize_hypvit_torch
  args:
    im_size: 32
    crop_size: 32


hydra_dir: ${logs_root}/${logs_folder}/


hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
    - pkg://oml.configs
