postfix: "feature_extractor"

seed: 42
precision: 16
accelerator: gpu
devices: 2

dataset_root: /path/to/dataset/  # <---- specify path to your dataset
logs_root: /path/to/logs/ # <---- specify path to your logs
dataframe_name: df.csv
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

num_workers: 20
cache_size: 0

transforms_train:
  name: augs_hypvit_torch
  args:
    im_size: 224

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

sampler:
  name: balance
  args:
    n_labels: 150
    n_instances: 4

bs_val: 256
max_epochs: 10000
valid_period: 5

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 10, 20, 30, 100]
  map_top_k: [5, 10]
  fmr_vals: []
  pfc_variance: []
  return_only_main_category: True
  visualize_only_main_category: True

log_images: False

metric_for_checkpointing: OVERALL/cmc/1

model:
  name: vit
  args:
    normalise_features: True
    use_multi_scale: False
    weights: vits16_dino
    arch: vits16

criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: 0.15
    reduction: mean
    miner:
      name: hard_triplets
      args: {}

optimizer:
  name: adamw
  args:
    lr: 1e-5


scheduling: null


# To use neptune you should also specify NEPTUNE_API_TOKEN in
# .env file or via `export NEPTUNE_API_TOKEN=...`
neptune_project: null


hydra_dir: ${logs_root}/${logs_folder}/

tags:
  - ${postfix}

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
   - pkg://oml.configs
