postfix: "feature_extractor"

seed: 42
precision: 16
accelerator: gpu
devices: 2
find_unused_parameters: False


datasets:
  name: oml_image_dataset
  args:
    dataset_root: /path/to/dataset/  # <---- specify path to your dataset
    dataframe_name: df.csv
    cache_size: 0
    transforms_train:
      name: augs_hypvit_torch
      args:
        im_size: 224

    transforms_val:
      name: norm_resize_hypvit_torch
      args:
        im_size: 224
        crop_size: 224

logs_root: /path/to/logs/ # <---- specify path to your logs
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

num_workers: 20

sampler:
  name: balance
  args:
    n_labels: 150
    n_instances: 4

bs_val: 256
max_epochs: 10000
valid_period: 5

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 10, 20, 30, 100]
  map_top_k: [5, 10]
  fmr_vals: []
  pcf_variance: []
  return_only_overall_category: True
  visualize_only_overall_category: True

log_images: False

metric_for_checkpointing: OVERALL/cmc/1
mode_for_checkpointing: max

extractor:
  name: vit
  args:
    normalise_features: True
    use_multi_scale: False
    weights: vits16_dino
    arch: vits16

criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: 0.15
    reduction: mean
    miner:
      name: hard_triplets
      args: {}

optimizer:
  name: adamw
  args:
    lr: 1e-5


scheduling: null


logger:
  name: wandb  # requires <WANDB_API_KEY> as global env
  args:
    project: "test_project"


hydra_dir: ${logs_root}/${logs_folder}/

tags:
  - ${postfix}

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
   - pkg://oml.configs
  job:
    chdir: True
