name: concat_siamese
args:
  extractor:
    name: resnet
    args:
      arch: resnet50_projector
      gem_p: 7.0
      remove_fc: True
      normalise_features: False
      weights: resnet50_moco_v2
  mlp_hidden_dims: [20, 20]
  use_tta: True
  weights: null
