name: trivial_distance_siamese
args:
  extractor:
    name: resnet
    args:
      arch: resnet50_projector
      gem_p: 7.0
      remove_fc: True
      normalise_features: False
      weights: resnet50_moco_v2
