accelerator: gpu
devices: 1

dataset_root: data/CARS196/
dataframe_name: df.csv
features_file: ${dataset_root}/features.json

logs_root: logs/CARS196/

batch_size: 256
num_workers: 8

transforms:
  name: norm_resize_albu
  args:
    im_size: 224

model:
  name: vit
  args:
    arch: vits16
    normalise_features: False
    use_multi_scale: False
    weights: vits16_cars

log_images: False

hydra:
  searchpath:
   - pkg://oml.configs
