accelerator: gpu
devices: 1

dataset_root: data/Stanford_Online_Products/
dataframe_name: df.csv
features_file: ${dataset_root}/features.json

logs_root: logs/Stanford_Online_Products/

batch_size: 512
num_workers: 20

transforms:
  name: norm_resize_albu
  args:
    im_size: 224
    crop_size: 224

model:
  name: vit
  args:
    arch: vits16
    normalise_features: True
    use_multi_scale: False
    weights: vits16_sop

log_images: False

hydra:
  searchpath:
   - pkg://oml.configs
