postfix: metric_learning

seed: 42
precision: 32
accelerator: gpu
devices: 1

dataframe_name: df_no_bboxes.csv
dataset_root: data/DeepFashion_InShop/
logs_root: logs/DeepFashion_InShop/
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

show_dataset_warnings: False

num_workers: 20
cache_size: 0

transforms_train:
  name: augs_hypvit_torch
  args:
    im_size: 224

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

sampler: null
bs_train: 128

bs_val: 256
max_epochs: 10000
valid_period: 1

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1]
  map_top_k: [5]
  pfc_variance: [0.5, 0.9, 0.99]
  return_only_main_category: True
  visualize_only_main_category: True

log_images: True

metric_for_checkpointing: OVERALL/cmc/1

extractor:
  name: vit_clip
  args:
    arch: vitb16_224
    weights: openai_vitb16_224
    normalise_features: False

criterion:
  name: arcface
  args:
    smoothing_epsilon: 0.0
    m: 0.4
    s: 64
    in_features: 512
    num_classes: 3985

optimizer:
  name: adam
  args:
    lr: 1e-5


scheduling: null


# To use neptune you should also specify NEPTUNE_API_TOKEN in
# .env file or via `export NEPTUNE_API_TOKEN=...`
neptune_project: null


hydra_dir: ${logs_root}/${logs_folder}/

tags:
  - ${postfix}
  - deepfashion

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
   - pkg://oml.configs
