postfix: metric_learning

seed: 42
precision: 32
accelerator: gpu
devices: 1
find_unused_parameters: False

dataframe_name: df_with_bboxes.csv
dataset_root: data/CUB_200_2011/
logs_root: logs/CUB_200_2011/
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

num_workers: 20
cache_size: 0

transforms_train:
  name: augs_albu
  args:
    im_size: 224

transforms_val:
  name: norm_resize_albu
  args:
    im_size: 224

sampler:
  name: balance
  args:
    n_labels: 8
    n_instances: 4

bs_val: 256
max_epochs: 10000
valid_period: 5

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1]
  map_top_k: [5]
  fmr_vals: [0.01]
  pcf_variance: [0.5, 0.9, 0.99]
  return_only_overall_category: True
  visualize_only_overall_category: True

log_images: False

metric_for_checkpointing: OVERALL/cmc/1

extractor:
  name: vit
  args:
    normalise_features: False
    use_multi_scale: False
    weights: vits16_dino
    arch: vits16

criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: null
    reduction: mean
    miner:
      name: triplets_with_memory
      args:
        bank_size_in_batches: 50
        tri_expand_k: 3

optimizer:
  name: adam
  args:
    lr: 1e-5  # if you provide scheduler this parameter will be ignored

scheduling: null

logger:
  name: wandb  # requires <WANDB_API_KEY> as global env
  args:
    project: "test_project"

hydra_dir: ${logs_root}/${logs_folder}/

tags:
  - ${postfix}
  - cub

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
    - pkg://oml.configs
  job:
    chdir: True
