accelerator: gpu
precision: 32
devices: 1

dataset_root: /home/daloro/data/DeepFashion_InShop/
dataframe_name: df.csv

logs_root: /home/daloro/logs/DeepFashion_InShop/

bs_val: 512
num_workers: 10

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

model:
  name: vit
  args:
    arch: vits16
    normalise_features: False
    use_multi_scale: False
    weights: vits16_inshop

postprocessor:
  name: pairwise_images
  args:
    top_n: 5
    pairwise_model:
      name: concat_siamese
      args:
        mlp_hidden_dims: [192]
        weights: /home/daloro/python_projects/open-metric-learning/postprocessor.ckpt  # 0.9407792687416077 # 0.9404 (after swap)
        extractor:
          name: vit
          args:
            arch: vits16
            normalise_features: False
            use_multi_scale: False
            weights: null
    transforms:
      name: norm_resize_hypvit_torch
      args:
        im_size: 224
        crop_size: 224
    num_workers: ${num_workers}
    batch_size: ${bs_val}
    verbose: True
    use_fp16: True

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 5]
  map_top_k: [5]
  fmr_vals: []
  precision_top_k: [5]
  pfc_variance: []
  return_only_main_category: True
  visualize_only_main_category: True

log_images: False

hydra:
  searchpath:
   - pkg://oml.configs
