accelerator: gpu
precision: 32
devices: 1

dataset_root: /nydl/data/DeepFashion_InShop/
dataframe_name: df.csv

logs_root: /nydl/logs/DeepFashion_InShop/

bs_val: 128
num_workers: 20

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

model:
  name: vit
  args:
    arch: vits16
    normalise_features: True
    use_multi_scale: False
    weights: /nydl/logs/8feb/InShop/2023-02-14_10-31-24_inshop_no_categories/checkpoints/best.ckpt

postprocessor:
  name: pairwise_images
  args:
    top_n: 5
    pairwise_model:
      name: concat_siamese
      args:
        mlp_hidden_dims: [192]
        weights: /nydl/logs/8feb/InShop/2023-02-15_12-12-36_postprocessing_no_categories/checkpoints/best_fixed.ckpt
        extractor:
          name: vit
          args:
            arch: vits16
            normalise_features: False
            use_multi_scale: False
            weights: null
    transforms:
      name: norm_resize_hypvit_torch
      args:
        im_size: 224
        crop_size: 224
    num_workers: ${num_workers}
    batch_size: ${bs_val}
    verbose: True
    use_fp16: True

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 10, 20, 30, 100]
  map_top_k: [5, 10]
  fmr_vals: []
  precision_top_k: []
  pfc_variance: []
  return_only_main_category: True
  visualize_only_main_category: True

log_images: False

hydra:
  searchpath:
   - pkg://oml.configs
