accelerator: gpu
devices: 2
precision: 32

dataset_root: /nydl/data/Stanford_Online_Products/
dataframe_name: df.csv

logs_root: /nydl/logs/Stanford_Online_Products/

bs_val: 128
num_workers: 20

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

model:
  name: vit
  args:
    arch: vits16
    normalise_features: True
    use_multi_scale: False
    weights: vits16_sop

postprocessor:
  name: pairwise_images
  args:
    top_n: 5
    pairwise_model:
      name: concat_siamese
      args:
        mlp_hidden_dims: [192]
        weights: /nydl/logs/8feb/Stanford_Online_Products/2023-02-08_14-13-30_postprocessing/checkpoints/best.ckpt
        extractor:
          name: vit
          args:
            arch: vits16
            normalise_features: False
            use_multi_scale: False
            weights: null
    transforms:
      name: norm_resize_hypvit_torch
      args:
        im_size: 224
        crop_size: 224
    num_workers: ${num_workers}
    batch_size: ${bs_val}
    verbose: True
    use_fp16: True

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  map_top_k: [5]
  fmr_vals: []
  precision_top_k: [5]
  pfc_variance: [0.5, 0.9, 0.99]
  return_only_main_category: True
  visualize_only_main_category: True

log_images: False

hydra:
  searchpath:
   - pkg://oml.configs
