name: Tests in Docker (3.8)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  all_tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Building docker
      run: |
        make docker_build RUNTIME=cpu
    - name: Running all tests
      run: |
        make docker_all_tests RUNTIME=cpu WANDB_API_KEY=${{ secrets.WANDB_API_KEY }} NEPTUNE_API_TOKEN=${{ secrets.NEPTUNE_API_TOKEN }}
