name: Push to PyPI

on:
  pull_request:
    tags:
      - release.*
  push:
    tags:
      - release.*

jobs:
  publish_on_pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Exit if not on main branch
      if: endsWith(github.ref, 'release') == false
      run: exit -1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"
    - name: Build wheel
      run: |
        make build_wheel
    - name: Push the distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        repository_url: https://upload.pypi.org/legacy/
        skip_existing: true

  test_installation_from_pypi:
    runs-on: ubuntu-latest
    needs: publish_on_pypi
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8.0"
    - name: Installation
      run: |
        make pip_install_actual_oml
        python3 -c "from oml.losses.triplet import TripletLoss"
