postfix: metric_learning

seed: 42
precision: 16
accelerator: gpu
devices: 2
find_unused_parameters: False

dataframe_name: df.csv
dataset_root: data/Stanford_Online_Products/
logs_root: logs/Stanford_Online_Products/
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

num_workers: 20
cache_size: 0

transforms_train:
  name: augs_hypvit_torch
  args:
    im_size: 224

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

sampler:
  name: category_balance
  args:
    n_labels: 32
    n_instances: 6
    n_categories: 3
    resample_labels: True
    weight_categories: True

bs_val: 256
max_epochs: 10000
valid_period: 1

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1]
  map_top_k: [5]
  fmr_vals: []  # Since SOP is a big dataset you should be careful with increasing of the memory footprint, which is needed to calculate fmr
  pcf_variance: [0.5, 0.9, 0.99]
  return_only_overall_category: True
  visualize_only_overall_category: True

log_images: False

metric_for_checkpointing: OVERALL/cmc/1
mode_for_checkpointing: max

extractor:
  name: vit
  args:
    normalise_features: True
    use_multi_scale: False
    weights: vits16_dino
    arch: vits16

criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: 0.15
    reduction: mean
    miner:
      name: hard_triplets
      args: {}

optimizer:
  name: adam
  args:
    lr: 1e-5  # if you provide scheduler this parameter will be ignored

scheduling: null


logger:
  name: wandb  # requires <WANDB_API_KEY> as global env
  args:
    project: "test_project"


hydra_dir: ${logs_root}/${logs_folder}/

tags:
  - ${postfix}
  - sop

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
   - pkg://oml.configs
  job:
    chdir: True
