postfix: ""

seed: 42
precision: 32
accelerator: gpu
devices: 2

dataset_root: /nydl/data/mock_dataset/
dataframe_name: df.csv
logs_root: /nydl/data/mock_dataset/logs
logs_folder: ${now:%Y-%m-%d_%H-%M-%S}_${postfix}

num_workers: 0
max_epochs: 1000
valid_period: 1
bs_val: 256

metric_for_checkpointing: OVERALL/cmc/1

top_n: 5
extractor:
  name: vit
  args:
    normalise_features: True
    use_multi_scale: False
    weights: vits16_dino
    arch: vits16

freeze_n_epochs: 1

optimizer:
  name: adam
  args:
    lr: 5e-6

scheduling: null

sampler:
  name: category_balance
  args:
    n_labels: 2
    n_instances: 2
    n_categories: 1
    resample_labels: True
    weight_categories: True

transforms_train:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224


transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

transforms_extraction:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

metric_args:
  cmc_top_k: [1]

hydra_dir: ${logs_root}/${logs_folder}/

neptune_project: NEWYORKER/similarity-api

tags:
  - mock
  - postprocessing
  - node1

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
    - pkg://oml.configs
